name: Test workflow

on: [push]

permissions:
  contents: read
  issues: write

# defaults:
#   run:
#     working-directory: prime-router

jobs:
  create_issue:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - name: Install depcheck
        run: |
          npm install -g depcheck
      
      - name: Check Out Changes
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Run depcheck
        run: |
          cd frontend-react
          depcheck

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{ steps.date.outputs.today }}
          body: |
            ## This week's TODO

            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard

          labels: |
            meeting
            weekly